[tool.poetry]
name = "romm"
version = "1.9"
description = ""
authors = ["zurdi <zurdizurdo25@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "2.31.0"
fastapi = "0.95.1"
uvicorn = "0.22.0"
websockets = "11.0.3"
python-socketio = "5.8.0"
SQLAlchemy = "2.0.12"
alembic = "1.10.4"
PyYAML = "6.0"
Unidecode = "1.3.6"
emoji = "2.2.0"
python-dotenv = "1.0.0"
ipdb = "0.13.13"
fastapi-pagination = "^0.12.4"
sqlakeyset = "^2.0.1684285512"
pydash = "^7.0.6"
pytest = "^7.4.0"
pytest-env = "^0.8.2"
pytest-vcr = "^1.0.2"
pytest-mock = "^3.11.1"
mariadb = "1.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
