[tool.poetry]
package-mode = false
name = "romm"
version = "0.0.1"
description = "A beautiful, powerful, self-hosted rom manager"
license = "GNU GPLv3"
repository = "https://github.com/zurdi15/romm"
authors = [
    "Zurdi <https://github.com/zurdi15/>",
    "Georges-Antoine Assi <contact@me.gantoine.com>",
]

[tool.poetry.dependencies]
python = "^3.11"
requests = "2.31.0"
fastapi = "0.110.0"
uvicorn = "0.28.0"
websockets = "12.0"
python-socketio = "5.11.1"
SQLAlchemy = {extras = ["mypy"], version = "^2.0.28"}
alembic = "1.13.1"
PyYAML = "6.0.1"
Unidecode = "1.3.8"
emoji = "2.10.1"
python-dotenv = "1.0.1"
ipdb = "0.13.13"
fastapi-pagination = "^0.12.19"
sqlakeyset = "^2.0.1708907391"
pydash = "^7.0.7"
mariadb = "1.1.10"
rq = "^1.16.1"
aioredis = "^2.0.1"
types-pyyaml = "^6.0.12.20240311"
types-requests = "^2.31.0.20240311"
mypy = "^1.9.0"
types-redis = "^4.6.0.20240311 "
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
itsdangerous = "^2.1.2"
stream-zip = "^0.0.71"
rq-scheduler = "^0.13.1"
starlette-csrf = "^3.0.0"
httpx = "^0.27.0"
python-multipart = "^0.0.9"
types-python-jose = "^3.3.4.20240106"
types-passlib = "^1.7.7.20240311"
watchdog = "^4.0.0"
xmltodict = "^0.13.0"
Pillow = "10.2.0"
numpy = "^1.26.4"

[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"
pytest-env = "^1.1.3"
pytest-vcr = "^1.0.2"
pytest-mock = "^3.12.0"
pytest-asyncio = "^0.23.5"

[tool.mypy]
plugins = "sqlalchemy.ext.mypy.plugin"
check_untyped_defs = true
exclude = ["tests", "alembic"]
