[tool.poetry]
name = "RomM"
version = "2.0.0"
description = "RomM (Rom Manager) is a web based retro roms manager integrated with IGDB."
authors = ["zurdi <zurdizurdo25@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "2.31.0"
fastapi = "0.95.1"
uvicorn = "0.22.0"
websockets = "11.0.3"
python-socketio = "5.8.0"
SQLAlchemy = {extras = ["mypy"], version = "^2.0.19"}
alembic = "1.10.4"
PyYAML = "6.0.1"
Unidecode = "1.3.6"
emoji = "2.2.0"
python-dotenv = "1.0.0"
ipdb = "0.13.13"
fastapi-pagination = "^0.12.4"
sqlakeyset = "^2.0.1684285512"
pydash = "^7.0.6"
mariadb = "1.1.7"
rq = "^1.15.1"
aioredis = "^2.0.1"
types-pyyaml = "^6.0.12.11"
types-requests = "^2.31.0.2"
mypy = "^1.4.1"
types-redis = "^4.6.0.3"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
itsdangerous = "^2.1.2"
stream-zip = "^0.0.67"
rq-scheduler = "^0.13.1"
starlette-csrf = "^3.0.0"
httpx = "^0.24.1"
python-multipart = "^0.0.6"
types-python-jose = "^3.3.4.8"
types-passlib = "^1.7.7.13"
watchdog = "^3.0.0"
xmltodict = "^0.13.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
pytest-env = "^0.8.2"
pytest-vcr = "^1.0.2"
pytest-mock = "^3.11.1"
pytest-asyncio = "^0.21.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
plugins = "sqlalchemy.ext.mypy.plugin"
check_untyped_defs = true
exclude = ["tests", "alembic"]
