# This config file is compatible with Batocera or Retrobat-based set-ups
# Rename this file to `config.yml`, copy it to a `config` folder, and mount that folder as per the docker-compose.example.yml
# Only uncomment the lines you want to use/modify, or add new ones where needed
exclude:
  platforms: []
  roms:
    multi_file:
      names: []
      parts:
        extensions: []
        names: []
    single_file:
      extensions: []
      names: []
filesystem: {}
system:
  platforms:
    3do: 3do
    3ds: 3ds
    adam: colecoadam
    advision: adventure-vision
    amiga1200: amiga
    amiga4000: amiga
    amiga500: amiga
    amigacd32: amiga-cd32
    amigacdtv: amiga-cd32
    amstradcpc: acpc
    apfm1000: apf
    apple2: appleii
    apple2gs: apple-iigs
    arcadia: arcadia-2001
    archimedes: acorn-archimedes
    arduboy: arduboy
    astrocade: astrocade
    atari2600: atari2600
    atari5200: atari5200
    atari7800: atari7800
    atari800: atari
    atarist: atari-st
    atom: atom
    atomiswave: arcade
    bbcmicro: bbcmicro
    c128: c128
    c20: vic-20
    c64: c64
    camplynx: camputers-lynx
    cdi: philips-cd-i
    channelf: fairchild-channel-f
    coco: trs-80-color-computer
    colecovision: colecovision
    cplus4: c-plus-4
    cps1: cps1
    cps2: cps2
    cps3: cps3
    crvision: creativision
    daphne: daphne
    dos: dos
    dreamcast: dc
    easyrpg: rpgmaker
    fbneo: arcade
    fds: fds
    fm7: fm-7
    fmtowns: fm-towns
    gamate: gamate
    gameandwatch: g-and-w
    gamecom: game-dot-com
    gamecube: ngc
    gamegear: gamegear
    gb: gb
    gb2players: gb
    gba: gba
    gba2players: gba
    gbc: gbc
    gbc2players: gbc
    gp32: gp32
    gzdoom: doom
    intellivision: intellivision
    jaguar: jaguar
    jaguarcd: atari-jaguar-cd
    lcdgames: handheld-electronic-lcd
    lynx: lynx
    mame: arcade
    mastersystem: sms
    megadrive: genesis
    megadrive-msu: genesis
    megaduck: megaduck
    model2: arcade
    model3: arcade
    msx1: msx
    msx2: msx2
    msx2+: msx2
    n64: n64
    n64dd: 64dd
    naomi: arcade
    naomi2: arcade
    nds: nds
    neogeo: neogeoaes
    neogeocd: neo-geo-cd
    nes: nes
    ngp: neo-geo-pocket
    ngpc: neo-geo-pocket-color
    oricatmos: oric
    pc88: pc-8800-series
    pc98: pc-9800-series
    pcengine: tg16
    pcenginecd: turbografx-cd
    pcfx: pc-fx
    pet: cpet
    pokemini: pokemon-mini
    prboom: doom
    ps2: ps2
    ps3: ps3
    ps4: ps4
    psp: psp
    psvita: psvita
    psx: psx
    pv1000: casio-pv-1000
    samcoupe: sam-coupe
    satellaview: satellaview
    saturn: saturn
    scummvm: scummvm
    scv: epoch-super-cassette-vision
    sega32x: sega32
    segacd: segacd
    sg1000: sg1000
    sgb: gbc
    snes: snes
    snes-msu: snes
    spectravideo: spectravideo
    supergrafx: supergrafx
    supervision: supervision
    supracan: super-acan
    switch: switch
    thomson: thomson-mo5
    ti99: ti-99
    tic80: tic
    triforce: arcade
    tutor: tomy-tutor
    vectrex: vectrex
    virtualboy: virtualboy
    vsmile: vsmile
    wii: wii
    wiiu: wiiu
    windows: win
    wswan: wonderswan
    wswanc: wonderswan-color
    x1: x1
    x68000: sharp-x68000
    xbox: xbox
    xbox360: xbox360
    zmachine: z-machine
    zx81: zx81
    zxspectrum: zxs
  versions: {}
