# This config file is compatible with Batocera or Retrobat-based set-ups
# Rename this file to `config.yml`, copy it to a `config` folder, and mount that folder as per the docker-compose.example.yml
# Only uncomment the lines you want to use/modify, or add new ones where needed
exclude:
  platforms: []
  roms:
    multi_file:
      names: []
      parts:
        extensions: []
        names: []
    single_file:
      extensions: []
      names: []
filesystem: {}
system:
  platforms:
    3do: 3do
    3ds: 3ds
    adam: colecoadam
    advision: adventure-vision
    amiga1200: amiga
    amiga4000: amiga
    amiga500: amiga
    amigacd32: amiga-cd32
    amigacdtv: amiga-cd32
    amstradcpc: acpc
    apfm1000: apf
    apple2: appleii
    apple2gs: apple-iigs
    arcadia: arcadia-2001
    archimedes: acorn-archimedes
    arduboy: arduboy
    astrocde: astrocade
    atari2600: atari2600
    atari5200: atari5200
    atari7800: atari7800
    atari800: atari8bit
    atarist: atari-st
    atom: atom
    atomiswave: arcade
    bbc: bbcmicro
    c128: c128
    c20: vic-20
    c64: c64
    camplynx: camputers-lynx
    cdi: philips-cd-i
    channelf: fairchild-channel-f
    coco: trs-80-color-computer
    commander-x16: commander-x16
    colecovision: colecovision
    cplus4: c-plus-4
    cps1: cps1
    cps2: cps2
    cps3: cps3
    crvision: creativision
    daphne: daphne
    dos: dos
    dreamcast: dc
    easyrpg: rpgmaker
    electron: acorn-electron
    fbneo: arcade
    fds: fds
    flash: browser
    fm7: fm-7
    fmtowns: fm-towns
    gamate: gamate
    gameandwatch: g-and-w
    gamecom: game-dot-com
    gamecube: ngc
    gamegear: gamegear
    gamepock: epoch-game-pocket-computer
    gb: gb
    gb2players: gb
    gba: gba
    gba2players: gba
    gbc: gbc
    gbc2players: gbc
    gmaster: hartung
    gp32: gp32
    gzdoom: doom
    intellivision: intellivision
    jaguar: jaguar
    jaguarcd: atari-jaguar-cd
    lcdgames: handheld-electronic-lcd
    lindbergh: model2
    lynx: lynx
    macintosh: mac
    mame: arcade
    mastersystem: sms
    megadrive: genesis
    megadrive-msu: genesis
    megaduck: mega-duck-slash-cougar-boy
    model2: arcade
    model3: arcade
    msu-md: genesis
    msx1: msx
    msx2: msx2
    msx2+: msx2plus
    msxturbor: msx-turbo
    mugen: mugen
    multivision: multivision
    n64: n64
    n64dd: 64dd
    namco22: arcade
    namco2x6: arcade
    naomi: arcade
    naomi2: arcade
    nds: nds
    neogeo: neogeoaes
    neogeocd: neo-geo-cd
    nes: nes
    ngp: neo-geo-pocket
    ngpc: neo-geo-pocket-color
    odyssey2: odyssey
    openbor: openbor
    oricatmos: atmos
    pc88: pc-8800-series
    pc98: pc-9800-series
    pcengine: tg16
    pcenginecd: turbografx-cd
    pcfx: pc-fx
    pet: cpet
    pico: sega-pico
    plugnplay: plug-and-play
    pokemini: pokemon-mini
    prboom: doom
    ps: psx
    ps2: ps2
    ps3: ps3
    ps3-psn: ps3
    ps4: ps4
    ps5: ps5
    psp: psp
    pspminis: psp-minis
    psvita: psvita
    psvr: psvr
    psx: psx
    pv1000: casio-pv-1000
    samcoupe: sam-coupe
    satellaview: satellaview
    saturn: saturn
    scummvm: scummvm
    scv: epoch-super-cassette-vision
    sega32x: sega32
    segacd: segacd
    segastv: stv
    sg1000: sg1000
    sgb: gbc
    snes: snes
    snes-msu1: snes
    socrates: socrates
    spectravideo: spectravideo
    sufami: sufami-turbo
    supergrafx: supergrafx
    supervision: supervision
    supracan: super-acan
    switch: switch
    thomson: thomson-mo5
    tic80: tic
    triforce: arcade
    tutor: tomy-tutor
    uzebox: uzebox
    vc4000: vc-4000
    vectrex: vectrex
    videopacplus: videopac-g7400
    virtualboy: virtualboy
    vis: vis
    vpinball: pinball
    vsmile: vsmile
    wasm4: wasm-4
    wii: wii
    wiiu: wiiu
    wiiware: wii
    windows: win
    wswan: wonderswan
    wswanc: wonderswan-color
    x1: x1
    x68000: sharp-x68000
    xbox: xbox
    xbox360: xbox360
    xegs: atari-xegs
    zx81: zx81
    zxspectrum: zxs
  versions: {}
